### ISSUE TITLE
Launcher doesn't exit cleanly on Linux

### ISSUE THREAD

**Issue by LiamDawe** [shusaura85/notparadoxlauncher#11]
On Manjaro Linux, the launcher doesn't seem to exit cleanly. I have to manually kill the left over process.

It works fine, installs fine and so on but it does give this:

> [liam@liam-manjaro ~]$ /home/liam/Downloads/Linux.Not.Paradox.Launcher.v1.2.0.x64/launcher
An unhandled exception occurred at $00007F9CC756942C:
EAccessViolation: 
  $00007F9CC756942C

If you need more info, let me know.

**Comment by shusaura85** [comment]
Thanks for the report. Please let me know what edition and version of Manjaro you're using.  
I'll set up a VM with Manjaro sometime this week to test it out and see what I can do to fix it.

**Comment by LiamDawe** [comment]
Wow, thanks! This is just KDE Manjaro.

**Comment by shusaura85** [comment]
Just installed a copy of Manjaro KDE and can confirm the reported bug.  
From initial investigation, it would appear to be a problem between the compiled code and the KDE shell.  
  
Looking for solutions

**Comment by shusaura85** [comment]
I've released version 1.2.2 that although doesn't fix the actual bug (as the root cause appears to be in KDE (kio core), the launcher will invoke the kill command on it's own process id to fully close.  
  
The access violation will still appear but the launcher process will be properly terminated.  
  
As an extra I also changed the options window info text color (so now you can actually read them)
